504/config/urls.py
from django import urls
from django.contrib import admin
from django.urls import path
from django.urls.conf import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('web.urls'))
]

504/web/urls.py
from django.urls import path
from .views import FruitsListView, IndexView, FruitsView,  FruitsCreateView, FruitsDetailView

app_name = 'web'

urlpatterns = [
    path('index/', IndexView.as_view(), name='index'),
    # path('list/', FruitsListView.as_view(), name='list'),
    path('fruits/', FruitsView.as_view(), name='fruits'),
    path('fruits/new', FruitsCreateView.as_view(), name='fruitscreate'),
    path('fruits/<int:id>', FruitsDetailView.as_view(), name='fruitsdetail'),
]

504/templates/base.html
<!doctype html>
<html lang="ja">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">

    {% block title %}{% endblock %}
  </head>
  <body>
    {% block header %}{% endblock %}
    <div class="container">
        <div class="row">
          <div class="col-sm">
            {% block content %}{% endblock %}
          </div>
        </div>
      </div>

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    {% block js%}{% endblock %}

  </body>
</html>

504/templates/fruits.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    {% if object_list|length != 0 %}
      <span>件数：{{ object_list|length }}</span>
    {% endif %}
    <a class='btn btn-primary' href="{% url 'web:fruitscreate' %}">新規追加</a>
    <table class="table table-dark table-striped">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">果物名</th>
                <th scope="col">メモ</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            {% for item in object_list %}
            <tr>
                <td id='no'>{{ item.0 }}
                <td id='name'>{{ item.1 }}</td>
                <td id='memo'>{{ item.2 }}</td>
                <td>
                  <a class="btn btn-primary pl-2" href="{% url 'web:fruitsdetail' item.0 %}">更新</a>
                  <button class="btn btn-primary pl-2" id=delete{{ item.0 }} value={{ item.0 }}>削除</button>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock %}

{% block js %}
  <script>
    $(document).on('click', function(event) {
      let target = event.target.id;
      if (target.indexOf('delete') !== -1) {
        id = event.target.value;
        ajaxfunc(id)
      }
    })

    function ajaxfunc(id){
      // Ajax通信を開始
      url = "/fruits/" + id
      $.ajax({
        'url': url,
        'type': 'DELETE',
        'dataType': 'json',
        'data':  {
          'no': $('#no').val(),
          'name': $('#name').val(),
          'memo': $('#memo').val(),
        },
        'timeout': 5000,
      })
      .done(function(data) {
          // 通信成功時の処理を記述
          location.reload();
      })
      .fail(function() {
          // 通信失敗時の処理を記述
      });
    }
  </script>
{% endblock %}

504/templates/fruitscreate.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <div class="container bg-light">
      <h3>---新規登録---</h3>
      <form method="POST">
        {% csrf_token %}
        <div class="mb-3">
          {{ form.id.errors }}
          {{ form.id.label }}
          {{ form.id }}
        </div>
        <div class="mb-3">
          {{ form.name.errors }}
          {{ form.name.label }}
          {{ form.name }}
        </div>
        <div class="mb-3">
          {{ form.memo.errors }}
          {{ form.memo.label }}
          {{ form.memo }}
        </div>
        <button type="submit" class="btn btn-primary">登録</button>
      </form>
    </div>
{% endblock %}

504/templates/fruitslist.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">

    <title>title</title>
  </head>
  <body>
    <div class="container mt-5 p-lg-5 bg-light">
      {% if object_list|length != 0 %}
        <span>件数：{{ object_list|length }}</span>
      {% endif %}
      <table class="table table-dark table-striped">
          <thead>
              <tr>
                  <th scope="col">#</th>
                  <th scope="col">果物名</th>
                  <th scope="col">メモ</th>
              </tr>
          </thead>
          <tbody>
              {% for item in object_list %}
              <tr>
                  <td><a href="#">{{ item.0 }}</a></td>
                  <td>{{ item.1 }}</td>
                  <td>{{ item.2 }}</td>
              </tr>
              {% endfor %}
          </tbody>
      </table>
    </div>

    <class class="pagination">
      <span class="step-links">
        {% if page.has_previous %}
          <a href="?page={{ page.previous_page_number }}">前</a>
        {% endif %}
        <span class="current">
        {% for link_page in page.paginator.page_range %}
          {% if link_page == page_obj.number %}
              {{ link_page }}
          {% else %}
              {{ link_page }}
          {% endif %}
        {% endfor %}
        </span>
          {% if page.has_next %}
            <a href="?page={{ page.next_page_number }}">次</a>
          {% endif %}
      </span>
    </class>
    
    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>

  </body>
</html>

504/templates/fruitsupdate.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <div class="container bg-light">
      <h3>---データ更新---</h3>
      <form method="PUT" action="{% url 'web:fruitsdetail' id %}">
        {% csrf_token %}
        <div class="mb-3">
          {{ form.id.errors }}
          {{ form.id.label }}
          {{ form.id }}
        </div>
        <div class="mb-3">
          {{ form.name.errors }}
          {{ form.name.label }}
          {{ form.name }}
        </div>
        <div class="mb-3">
          {{ form.memo.errors }}
          {{ form.memo.label }}
          {{ form.memo }}
        </div>
        <button id="btnsend" class="btn btn-primary" type="submit">更新</button>
        <a class="btn btn-primary" href="{% url 'web:fruits' %}">戻る</a>
      </form>
    </div>
{% endblock %}

{% block js %}
  <script>
    $('#btnsend').on('click', function(){
      // Ajax通信を開始
      $.ajax({
        'url': '{% url "web:fruitsdetail" %}',
        'type': 'PUT',
        'dataType': 'json',
        // 'data':  {
        //   'id': $('#id').val(),
        //   'name': $('#name').val(),
        //   'memo': $('#memo').val(),
        // },
        'timeout': 5000,
      })
      .done(function(data) {
          // 通信成功時の処理を記述
      })
      .fail(function() {
          // 通信失敗時の処理を記述
          console.log('no')
      });
    })
  </script>
{% endblock %}

504/templates/index.html
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
  {{ dt }}
</body>
</html>