505/config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('web.urls')),
]

505/web/urls.py
from django.urls import path
from .views import IndexView, ItemCreateView, ItemUpdateView, UserView, UserCreateView, UserUpdateView, LoginView, LogoutView

app_name = 'web'

urlpatterns = [
    path('', LoginView.as_view(),name='login'), 
    path('logout/', LogoutView.as_view(), name='logout'), 
    path('index/', IndexView.as_view(), name='index'),
    path('item_create/', ItemCreateView.as_view(), name='item_create'),
    path('item_update/<int:pk>', ItemUpdateView.as_view(), name='item_update'),
    path('user/', UserView.as_view(), name='user'),
    path('user_create/', UserCreateView.as_view(), name='user_create'),
    path('user_update/<int:pk>', UserUpdateView.as_view(), name='user_update'),
]

505/templates/base.html
<!doctype html>
{% load static %}
<html lang="ja">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    {% block header %}{% endblock %}
    {% block title %}{% endblock %}
  </head>
  <body>
    {% block content %}{% endblock %}

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>

    {% block js %}{% endblock %}
  </body>
</html>

505/templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block header %}
<link rel="stylesheet" href="{% static 'index.css' %}">
{% endblock %}

{% block title %}
<title>商品一覧</title>
{% endblock %}

{% block content %}
  <div class="container mt-5 p-lg-5 bg-light">
    <h4>商品マスタ</h4>
    <div class="d-flex flex-row bd-highlight mb-3 form-control">
        <div class="col-5">
            <h5>メニュー</h5>
            <a type="button" href="{% url 'web:item_create' %}">商品登録</a>
        </div>
        <div class="col-5">
            <h5>マスタ</h5>
            <a type="button" href="{% url 'web:user' %}">ユーザーマスタ</a>
        </div>
        <div class="col-2">
            <div>
                <a type="button" href="{% url 'web:logout' %}">ログアウト</a>
            </div>
        </div>
    </div>
    <div class='form-control'>
        <form action="{% url 'web:index' %}" method="POST">
            {% csrf_token %}
            <h5>検索</h5>
            <div class="d-flex flex-row bd-highlight mb-3">
                <div class="form-content">
                    <label class="form-label">{{ form.item_no.label }}</label>
                    {{ form.item_no }}
                </div>
                <div class="form-content">
                    <label class="form-label">{{ form.item_nm.label }}</label>
                    {{ form.item_nm }}
                </div>
                <div class="form-content">
                    <label class="form-label">{{ form.register_from.label }}</label>
                    {{ form.register_from }}
                </div>
                <div class="form-content">
                    <label class="form-label">{{ form.register_to.label }}</label>
                    {{ form.register_to }}
                </div>
                <button type="submit" class="btn btn-primary form-btn">検索</button>  
            </div>  
        </form> 
    </div>
    <table class="table">
        <thead>
            <tr>
                <th scope="col">商品ID</th>
                <th scope="col">商品名</th>
                <th scope="col">登録日時</th>
            </tr>
        </thead>
        <tbody>
            {% for item in object_list %}
            <tr>
                <td><a href="{% url 'web:item_update' item.pk %}">{{ item.item_no }}</a></td>
                <td>{{ item.item_nm }}</td>
                <td>{{ item.register_dt|date:"Y/m/d" }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}

505/templates/item_create.html
{% extends 'base.html' %}
{% load static %}

{% block header %}
 <link rel="stylesheet" href="{% static 'index.css' %}">
{% endblock %}

{% block title %}
 <title>商品登録</title>
{% endblock %}

{% block content %}
  <div class="container mt-5 p-lg-5 bg-light">
    <h4>商品登録</h4>
    <div class='form-control'>
        <form action="#" method="POST">
            {% csrf_token %}
            <div class="content">
                <label class="label">{{ form.item_no.label }}</label>
                {{ form.item_no }}
            </div>
            <div class="content">    
                <label class="label">{{ form.item_nm.label }}</label>
                {{ form.item_nm }}
            </div>
            <div class="content">
                <label class="label">{{ form.del_flg.label }}</label>
                {{ form.del_flg }}
            </div>
            <div class="content">
                <label class="label">{{ form.register_dt.label }}</label>
                {{ form.register_dt }}
            </div>
            <div class="content">
                <label class="label">{{ form.version.label }}</label>
                {{ form.version }}
            </div>
            <div class="content">
                <a class="a-contents btn btn-primary" type="button" href="{% url 'web:index' %}">キャンセル</a>
                <button type="submit" class="btn btn-primary">登録</button>
            </div>
        </form> 
    </div>
</div>
{% endblock %}

505/templates/item_update.html
{% extends 'base.html' %}
{% load static %}

{% block header %}
 <link rel="stylesheet" href="{% static 'index.css' %}">
{% endblock %}

{% block title %}
 <title>商品更新</title>
{% endblock %}

{% block content %}
  <div class="container mt-5 p-lg-5 bg-light">
    <h4>商品登録</h4>
    <div class='form-control'>
        <form action="#" method="POST">
            {% csrf_token %}
            <div class="content">
                <label class="label">{{ form.item_no.label }}</label>
                {{ form.item_no }}
            </div>
            <div class="content">    
                <label class="label">{{ form.item_nm.label }}</label>
                {{ form.item_nm }}
            </div>
            <div class="content">
                <label class="label">{{ form.del_flg.label }}</label>
                {{ form.del_flg }}
            </div>
            <div class="content">
                <label class="label">{{ form.register_dt.label }}</label>
                {{ form.register_dt }}
            </div>
            <div class="content">
                <label class="label">{{ form.version.label }}</label>
                {{ form.version }}
            </div>
            <div class="content">
                <a class="a-contents btn btn-primary" type="button" href="{% url 'web:index' %}">キャンセル</a>
                <button type="submit" class="btn btn-primary" name="delete" value="delete">削除</button>
                <button type="submit" class="btn btn-primary" name="update" value="update">更新</button>
            </div>
        </form> 
    </div>
</div>
{% endblock %}

505/templates/login.html
{% extends 'base.html' %}
{% load static %}

{% block header %}
<link rel="stylesheet" href="{% static 'index.css' %}">
{% endblock %}

{% block title %}
<title>ログイン</title>
{% endblock %}

{% block content %} 
<div class="form-login">
    <div class="login-content">
        <h4>ログイン</h4>
        <form action="" method="POST">
            {% csrf_token %}
            {{ form.non_field_errors }}
            {{ errors }}
            <div class="login-content">
                <label class="login-label">{{ form.user_id.label }}</label>
                {{ form.user_id }}
                {{ form.user_id.errors }} 
            </div>
            <div class="login-content"> 
                <label class="login-label">{{ form.passwd.label }}</label>
                {{ form.passwd }}
                {{ form.passwd.errors }}  
            </div>
            <div class="login-content">
                <button type="submit" class="btn btn-success btn-lg btn-block" >ログイン</button>
                <input type="hidden" name="next" value="{{ next }}" />
            </div>
        </form>
    </div>
</div>


    
{% endblock %}

505/templates/user.html
{% extends 'base.html' %}
{% load static %}

{% block header %}
    <link rel="stylesheet" href="{% static 'index.css' %}">
{% endblock %}

{% block title %}
    <title>ユーザーマスタ</title>
{% endblock %}


{% block content %}
<div class="container mt-5 p-lg-5 bg-light">
    <h4>ユーザーマスタ</h4>
    <div class="d-flex flex-row bd-highlight mb-3 form-control">
        <div class="col-5">
            <h5>メニュー</h5>
            <a type="button" href="{% url 'web:user_create' %}">ユーザー登録</a>
        </div>
        <div class="col-5">
            <h5>マスタ</h5>
            <a href="{% url 'web:index' %}">商品マスタ</a>
        </div>
    </div>
    <div class='form-control'>
        <form action="{% url 'web:user' %}" method="POST">
            {% csrf_token %}
            <h5>検索</h5>
            <div class="d-flex flex-row bd-highlight mb-3">
                <div class="form-content">
                    <label class="form-label">{{ form.user_id.label }}</label>
                    {{ form.user_id }}
                </div>
                <div class="form-content">
                    <label class="form-label">{{ form.user_name.label }}</label>
                    {{ form.user_name }}
                </div>
                <div class="form-content">
                    <label class="form-label">{{ form.del_flg.label }}</label>
                    {{ form.del_flg }}
                </div>
                <button type="submit" class="btn btn-primary form-btn">検索</button>
            </div>  
        </form> 
    </div>
    <table class="table">
        <thead>
            <tr>
                <th class="th">ユーザーID</th>
                <th class="th">ユーザー名</th>
                <th class="th">有効フラグ</th>
                <th class="th">登録日時</th>
            </tr>
        </thead>
        <tbody>
            {% for item in object_list %}
            {% if item.del_flg == '1' %}
            <tr>
                <td style="background-color: #e0e0e0;"><a href="{% url 'web:user_update' item.pk %}">{{ item.user_id }}</a></td>
                <td style="background-color: #e0e0e0;">{{ item.user_name }}</td>
                <td style="background-color: #e0e0e0;">{{ item.del_flg }}</td>
                <td style="background-color: #e0e0e0;">{{ item.register_dt|date:"Y/m/d" }}</td>
            </tr>
            {% else %}
            <tr>
                <td><a href="{% url 'web:user_update' item.pk %}">{{ item.user_id }}</a></td>
                <td>{{ item.user_name }}</td>
                <td>{{ item.del_flg }}</td>
                <td>{{ item.register_dt|date:"Y/m/d" }}</td>
            </tr>
            {% endif %}
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}

505/templates/user_create.html
{% extends 'base.html' %}
{% load static %}

{% block header %}
 <link rel="stylesheet" href="{% static 'index.css' %}">
{% endblock %}

{% block title %}
 <title>ユーザー登録</title>
{% endblock %}

{% block content %}
  <div class="container mt-5 p-lg-5 bg-light">
    <h4>ユーザー登録</h4>
    <div class='form-control'>
        <form action="{% url 'web:user_create' %}" method="POST">
            {% csrf_token %}
            <div class="content">
                <label class="label">{{ form.user_id.label }}</label>
                {{ form.user_id }}
                {{ form.user_id.errors }} 
            </div>
            <div class="content">     
                <label class="label">{{ form.user_name.label }}</label>
                {{ form.user_name }}
            </div>
            <div class="content"> 
                <label class="label">{{ form.passwd.label }}</label>
                {{ form.passwd }}
                {{ form.passwd.errors }}  
            </div>
            <div class="content"> 
                <label class="label">{{ form.del_flg.label }}</label>
                {{ form.del_flg }}
            </div>
            <div class="content"> 
                <label class="label">{{ form.register_dt.label }}</label>
                {{ form.register_dt }}
            </div>
            <div class="content"> 
                <label class="label">{{ form.version.label }}</label>
                {{ form.version }}
            </div>
            <div class="content"> 
                <a class="a-contents btn btn-primary" type="button" href="{% url 'web:user' %}">キャンセル</a>
                <button type="submit" class="btn btn-primary">登録</button>
            </div>
        </form> 
    </div>
</div>
{% endblock %}

505/templates/user_update.html
{% extends 'base.html' %}
{% load static %}

{% block header %}
 <link rel="stylesheet" href="{% static 'index.css' %}">
{% endblock %}

{% block title %}
 <title>ユーザー更新</title>
{% endblock %}

{% block content %}
  <div class="container mt-5 p-lg-5 bg-light">
    <h4>ユーザー編集</h4>
    <div class='form-control'>
        <form action="#" method="POST">
            {% csrf_token %}
            <div class="content">
                <label class="label">{{ form.user_id.label }}</label>
                {{ form.user_id }}
            </div>
            <div class="content">   
                <label class="label">{{ form.user_name.label }}</label>
                {{ form.user_name }}
            </div>
            <div class="content"> 
                <label class="label">{{ form.passwd.label }}</label>
                {{ form.passwd }}
                {{ form.passwd.errors }}  
            </div>
            <div class="content">
                <label class="label">{{ form.del_flg.label }}</label>
                {{ form.del_flg }}
            </div>
            <div class="content">
                <label class="label">{{ form.register_dt.label }}</label>
                {{ form.register_dt }}
            </div>
            <div class="content">
                <label class="label">{{ form.version.label }}</label>
                {{ form.version }}
            </div>
            <div class="content">
                <a class="a-contents btn btn-primary" type="button" href="{% url 'web:user' %}">キャンセル</a>
                <button type="submit" class="btn btn-primary" name="update" value="update">更新</button>
                <button type="submit" class="btn btn-primary" name="delete" value="delete">削除</button>
            </div>
        </form> 
    </div>
</div>
{% endblock %}